### ISSUE TITLE
Avoid using Minecraft class in MsgControlSyncAll.

### ISSUE THREAD

**Issue by acaly** [LambdaInnovation/LIUtils#9]
In function `fromBytes` of `MsgControlSyncAll`, `Minecraft` class is used. Please move it to `Handler`, which is designed to do such work involving client side objects.

**Comment by WeAthFoLD** [comment]
BTW onMessage in Handler should be decorated with @SideOnly(Side,CLIENT) ^^

**Comment by acaly** [comment]
Buf should be read in fromBytes function.
